sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: XuCWccRTouyzzrAIh1OGTAfphuRT3oCtgcG51vzv8NikqHVId+IO3GOcEimo1q571ffMjDCG27M2Wr69Xcl8k4qRX+dr8HNedmkBYpwDj6SIdSGBp4aCV6FgnhXjTemklm65Fd5xsBYBuWuUg69afz6qZPgUntMnRIIjfwQx8NB519H/dJX2PkqiMWJ1pAvdz2DTnPiv871yjuhmoNUAl5UCAl1SWn/iZgcbsL/BBQV77U6t6/9773bx7+VLIIoPpy+EHgZs7TM28kg/cf1qEWZ/6ajGawVdGQJcU1jEsMK4TndOH6GPcTgaZ+uuER7XkyMigxs1cHiOVYfDfRbr5KBLIxO/+m3Nak7zzZMMPzSNQVCpXGW4szG+GHRSW7z7W1ESVi9I8jPW47uSNQkPUEz819LgvkLK3gircZEUC949BmcXsupDM9bCy3N02Cj6uN9hZ3HZu4nS6ExXliXeQoXssQH1JnUEQGii6cdokvEN/FJI0fIQ3ygP58pLCTK6RwjWj5jo1HccZSjA6JsFtcvHlyDhdmjH/EmthyFIamimKdxsJZ+SkzuJwEhicRDCdRGUN3eS/jMH8DJJpkvdceEY7J0alnHRBng21bVy5ZzEtyaDbTF+WmEik5529n75QAobRSVdfioRZ5UctOHle8geuRdeVnO3uyR7i33bFco=
    - secure: MvpMxAcKXzez2wHHrc72lwm4KgEZMgMyjGp6RX6OodpSdy/aQEZ+E45E2toOPM2UXRwuE+XEIQbjClzj7vAgCICid8TgAvpU9T0isu+gI8CUBAPaC7VI/MRwfjvIc2NWW06nrciY/K6atnAvOORJUWoWUoicAZoFPetFU31Hux/AIhBE15Qa7XVZ/Zjw36eYh6oWzzymF2OyGVSlXdhELB6dNGN8zBpQQB48WkzYyZjpp8D2Wjk0qjphKld0DuAsJ5H2mBZayVHzzF2dx3515529KQz1qywkDDNuqf5S4x1l9b2EtBXR7oJghUlpV37hzANzbnQiayz6fHIGv0JDJGhiNXilfw2ILIErDoAjB6ZavgM97uQFwGo5cWOSKeHh7vgOkO863085UheLTVHquD9rlgYGyeoznVWzoh9IRwQRJPlBvk2IuG0JN29BWPI06DDBKJBtMzaZrGTmZ130AflHoumA9FrOaj+LQ75YcHo8s1jN9ts3jqBNLVqgrr/ZIMv/iVTKmaYYBupExI+f2CARrKu159m4lQCq7pwpkT4iFlHDay8Qt8wmZfLgTVo5eUojbS1vQRhilcqpocnVR702GSJlIlpiQuwu0cxsRo9Kfqz4Cw3mf5ZFdVuH9fsmW+yiw4PhRlbbXQEDzuPk9JQ2ujOjtC+ydKNO95Rt9Ng=
    - secure: "Z4P+7/DuPTsUOgOTgjmvQJkQ0D68UXrbWO3ljiI2mClpkJJJlH16Q1hjplcu8bS7/9g9gKOAWrl80w3uMGo3Q8R2Aa1SC6zImvDi3C2xrAkMTeBZnJcCDw7UhB3gsDSDgeZyo4lZeIATeJLb/mlHOyB1a44PrnehZv/9lK2/STixibURZcNGhHMdDSGPUCD+E/iwaZAIPgMYYcn5Q9tfpHsBiV2z8wFmfI+Z0m4iqKeIq34AvjmRLnlNwpnn31uNUJHWOqBfwSyogHKUgpG09aGrw2B+TAJJoqmLC8nTPZzGAOGGLeAvASd3qbNuaJQDqfN8eM0bcVPu1es/UVf6SxLPXicu29l2AungQm8coeBOPfcTJY/hUuYCrPA2ncv0BAl9qMxoN4lTVdOnwpbHDAC3S0eLGIXHKPqHKOPIsk0Xn0vca9TUXygbz7tjMKu0JMdzeYYsIR+uU1FvrTZBh8C6DrxKzvPp2QEa0/ARkfNLAZST9QPY59R1PCGU3E5qvHlCRGKae2gpqvBpkpiTuswhCbRa47gqijGB1IEgqwmSuTdX18sLkrvu/siqkMpjPZpFrh+GWSy5I6swctfqIz2g691QI5DIbSQXTk5junQY0vNIAkKqVD/nep6Y4tEMCSQ2P/ier+bd+Ax3f9P6da4zC9x04DSETFHVKWylunI="
    - DOCKER_IMAGE_NAME=ismaelcabanas14/storeroom-rest-api

script:
  - "./gradlew check test integrationTest jacocoTestCoverageVerification jacocoTestReport --stacktrace"
  - sonar-scanner -X
  - cd storeroom-rest-api/
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker run -it -p 8000:8000 -d $DOCKER_IMAGE_NAME
  - cd ..
  - ./gradlew acceptanceTest
addons:
  sonarcloud:
    organization: ismaelcabanas-github
    token:
      secure: $SONAR_TOKEN
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TAG
  - docker push $DOCKER_IMAGE_NAME
